# Generated by Django 4.2.11 on 2024-03-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_movies_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.genres'),
        ),
    ]
